# Generated by Django 3.2.12 on 2022-09-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(max_length=200),
        ),
    ]
